image: conda/miniconda3

stages:
  - build
  - test
  - condabuild
  - deploy


.template_retry:
  retry:
    max: 2
    when: runner_system_failure


build_mr_linux:
  stage: build
  tags: 
    - linux
    - large
  script:
    - . "/builds/miniconda3/etc/profile.d/conda.sh"
    - mamba env update -f conda/env_linux.yaml
    - conda clean -p -t -y
    - conda activate gnomon-dev
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ..
    - make -j3 install
  extends: .template_retry
  only:
    - merge_requests

test_linux:
  stage: test
  needs: [build_mr_linux]
  tags: 
    - linux
    - large
  variables:
    GIT_CHECKOUT: "false"
  script:
    - . "/builds/miniconda3/etc/profile.d/conda.sh"
    - conda activate gnomon-dev
    - cd build
    - ctest -T test --timeout 120 --rerun-failed --output-on-failure --output-junit report.xml
  extends: .template_retry
  artifacts:
    when: always
    reports:
      junit: build/report.xml
  only:
    - merge_requests

build_mr_macos:
  stage: build
  tags: 
    - macos
    - large
  script:
    - source /Users/ci/miniconda3/etc/profile.d/conda.sh
    - mamba env update -f conda/env_macos.yaml
    - conda clean -p -t -y
    - conda activate gnomon-dev
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ..
    - make -j2 install
  extends: .template_retry
  only:
    - merge_requests

test_macos:
  stage: test
  needs: [build_mr_macos]
  tags: 
    - macos
    - large
  variables:
    GIT_CHECKOUT: "false"
  script:
    - source /Users/ci/miniconda3/etc/profile.d/conda.sh
    - conda activate gnomon-dev
    - cd build
    - ctest -T test --timeout 120 --rerun-failed --output-on-failure --output-junit report.xml
  extends: .template_retry
  artifacts:
    when: always
    reports:
      junit: build/report.xml
  only:
    - merge_requests


conda_build_linux:
  stage: condabuild
  tags: 
    - linux
    - large
  script:
    - . "/builds/miniconda3/etc/profile.d/conda.sh"
    - conda activate base
    - rm -rf conda-bld
    - mkdir conda-bld
    - conda mambabuild -c gnomon -c dtk-forge6 -c conda-forge conda/ --output-folder conda-bld/
  extends: .template_retry
  artifacts:
    paths:
      - conda-bld
  only:
    - master

conda_build_macos:
  stage: condabuild
  tags: 
    - macos
    - large
  script:
    - source /Users/ci/miniconda3/etc/profile.d/conda.sh
    - conda activate base
    - rm -rf conda-bld
    - mkdir conda-bld
    - conda mambabuild -c gnomon -c dtk-forge6 -c conda-forge conda/ --output-folder conda-bld/
  extends: .template_retry
  artifacts:
    paths:
      - conda-bld
  only:
    - master


conda_build_linux_develop:
  stage: condabuild
  tags: 
    - linux
    - large
  script:
    - . "/builds/miniconda3/etc/profile.d/conda.sh"
    - conda activate base  
    - mkdir conda-bld
    - conda mambabuild -c gnomon -c dtk-forge6 -c conda-forge conda/ --output-folder conda-bld/
  extends: .template_retry
  when: manual
  artifacts:
    paths:
      - conda-bld
  only:
    - develop


anaconda_linux_master:
  stage: deploy
  tags: 
    - linux
    - large
  needs: [conda_build_linux]
  variables:
    GIT_CHECKOUT: "false"
  script:
    - . "/builds/miniconda3/etc/profile.d/conda.sh"
    - conda activate base
    - mamba install -c conda-forge anaconda-client
    - cph transmute conda-bld/linux-64/gnomon-*.tar.bz2 .conda
    - anaconda --token=$ANACONDA_TOKEN upload conda-bld/linux-64/gnomon-*.conda --force --user gnomon
    - conda build purge
  extends: .template_retry
  only:
    - master

anaconda_macos_master:
  stage: deploy
  tags: 
    - macos
    - large
  needs: [conda_build_macos]
  variables:
    GIT_CHECKOUT: "false"
  script:
    - source /Users/ci/miniconda3/etc/profile.d/conda.sh
    - conda activate base
    - mamba install -c conda-forge anaconda-client
    - cph transmute conda-bld/osx-64/gnomon-*.tar.bz2 .conda
    - anaconda --token=$ANACONDA_TOKEN upload conda-bld/osx-64/gnomon-*.conda --force --user gnomon
    - conda build purge
  extends: .template_retry
  only:
    - master

anaconda_linux_develop :
  stage: deploy
  needs: [conda_build_linux_develop]
  tags: 
    - linux
    - large
  variables:
    GIT_CHECKOUT: "false"
  script:
    - . "/builds/miniconda3/etc/profile.d/conda.sh" 
    - conda activate base 
    - conda install -n base -c defaults conda python=3.9 -y
    - conda install conda-build anaconda-client curl
    #- curl -X POST https://ci.inria.fr/gnomon/job/gnomon-conda-mac-develop/build?token=$JENKINS_TOKEN
    - cph transmute conda-bld/linux-64/gnomon-*.tar.bz2 .conda
    - anaconda --token=$ANACONDA_TOKEN upload conda-bld/linux-64/gnomon-*.conda --force --user gnomon
  extends: .template_retry
  when: manual
  only:
    - develop


pages:
  stage: deploy
  tags:
    - linux
  script:
    - . "/builds/miniconda3/etc/profile.d/conda.sh" 
    - mamba env update -f conda/env_linux.yaml
    - conda activate gnomon-dev
    - mamba install -c conda-forge sphinx sphinx-design make matplotlib-base doxygen breathe=4.32
    - pip install "myst-parser>=2" sphinx-press-theme pydata-sphinx-theme
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ..
    - cd ../doc_md
    - make html
    - mv _build/html ../public
    - cd ../doc
    - make html
    - mkdir -p ../public/staging
    - cp -R build/html/* ../public/staging
  extends: .template_retry
  artifacts:
    paths:
      - public
  only:
    - master
    - develop
    - doc
