image: conda/miniconda3

.template_retry:
  retry:
    max: 2
    when: runner_system_failure

pages:
  stage: deploy
  script:
  - cd doc
  - conda update -n base -c defaults conda
  - conda install sphinx make matplotlib
  - make html
  - mv build/html ../public
  extends: .template_retry
  artifacts:
    paths:
    - public
  only:
  - master
  - develop
