## Version: $Id$
##
######################################################################
##
### Commentary:
##
######################################################################
##
### Change Log:
##
######################################################################
##
### Code:

add_subdirectory(gnomonGrowthSimulator)
add_subdirectory(gnomonOmeroClient)

######################################################################
### CMakeLists.txt ends here
