## Version: $Id$
##
######################################################################
##
### Commentary:
##
######################################################################
##
### Change Log:
##
######################################################################
##
### Code:

if(GNOMON_ENABLE_WIDGETS)
add_subdirectory(gnomon)
endif(GNOMON_ENABLE_WIDGETS)

######################################################################
### CMakeLists.txt ends here
