package:
  name: libgnomon
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.20.0') }}

source:
  #git_url: git@gitlab.inria.fr:gnomon/gnomon.git
  #git_tag: develop
  path: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - cmake >=3.17
    - make
    - python =3.9
    - numpy >=1.22
    - {{ compiler('cxx') }}              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libglvnd-devel') }}        # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libXt-devel') }}           # [linux]
    - {{ cdt('libSM-devel') }}           # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
    - {{ cdt('libICE-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]

  host:
    - qt >=6.2
    - dtk-core >=2.11
    - dtk-core-python >=2.8
    - dtk-imaging >=2.0
    - dtk-imaging-python >=2.0
    - dtk-log >=2.5
    - dtk-script >=2.5
    - python =3.9
    - numpy >=1.22
    - swig =4.0
    - vtk =9.1.0

  run:
    - qt >=6.2
    - dtk-core >=2.11
    - dtk-core-python >=2.8
    - dtk-imaging >=2.0
    - dtk-imaging-python >=2.0
    - dtk-log >=2.5
    - dtk-script >=2.5
    - python =3.9
    - numpy >=1.22
    - pillow
    - matplotlib
    - mongodb =4.0
    - pymongo =3.11
    - vtk =9.1.0

# app:
#   entry: gnomon # [linux]
#   entry: open ${PREFIX}/bin/gnomon # [osx]
#   summary: Gnomon is a computational platform to analyse and simulate the development of life forms in 3D
#   icon: gnomon_logo.png
#   type: desk

about:
  home: https://gnomon.gitlabpages.inria.fr/gnomon
  license: LGPL-3.0
  license_file: LICENSE
  summary: Gnomon is a computational platform to analyse and simulate the development of life forms in 3D
