#{% set build_string = '{}_py{}h{}_{}'.format(build_type, CONDA_PY, PKG_HASH, GIT_DESCRIBE_NUMBER) %}

package:
  name: gnomon-{{ build_type }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
#  string: {{ build_string }}
  script_env:
    - HAS_GUI=False # [build_type == lib]
    - HAS_GUI=True # [build_type == app]

requirements:
  build:
    - cmake >=3.20
    - make
    - python
    - numpy {{numpy}}
    - {{ compiler('cxx') }}              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libglvnd-devel') }}        # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libXt-devel') }}           # [linux]
    - {{ cdt('libSM-devel') }}           # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
    - {{ cdt('libICE-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - libxkbfile                         # [linux]
    - libwebp=1.2.2

  host:
    - qt6-main >=6.5,<7
    - dtk-forge6::vtk =9.2.6
    - pyside6
    - dtk-core >=2.13
    - dtk-core-python >=2.8
    - dtk-imaging >=2.0
    - dtk-imaging-python >=2.0
    - dtk-log >=2.5
    - dtk-script >=2.5
    - python
    - numpy {{numpy}}
    - swig >=4.1

  run:
    - qt6-main >=6.5,<7
    - dtk-forge6::vtk =9.2.6
    - pyside6
    - dtk-core >=2.13
    - dtk-core-python >=2.8
    - dtk-imaging >=2.0
    - dtk-imaging-python >=2.0
    - dtk-plugins-imaging >=2.0
    - dtk-log >=2.5
    - dtk-script >=2.5
    - python
    - numpy {{numpy}}
    - pymongo
    - jinja2
    - swig >=4.1
    - importlib_metadata       # [build_type == app]
    - matplotlib-base=3.5.1    # [build_type == app]
    - qtpy=2.0                 # [build_type == app]
    - qtconsole-base=5.2       # [build_type == app]
    - jedi=0.18.2              # [build_type == app]
    - python-lsp-server=1.7.1  # [build_type == app]
    - pip                      # [build_type == app]


about:
  home: https://gnomon.gitlabpages.inria.fr/gnomon
  license: LGPL-3.0
  license_file: LICENSE
  summary: Gnomon is a computational platform to analyse and simulate the development of life forms in 3D
