package:
  name: gnomon
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - cmake >=3.17
    - make
    - {{ compiler('cxx') }}              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libglvnd-devel') }}        # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libXt-devel') }}           # [linux]
    - {{ cdt('libSM-devel') }}           # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
    - {{ cdt('libICE-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxshmfence')}}           # [linux]
    - {{ cdt('libxshmfence-devel')}}     # [linux]
    - libxkbfile                         # [linux]
    - libwebp=1.2.2

  host:
    - qt=6.2.2
    - python

  run:
    - qt=6.2.2
    - python
    - importlib_metadata
    - numpy {{numpy}}
    - matplotlib-base=3.5.1
    - gnomon_package_data=0.5.0
    - gnomon_package_tissueimage=0.5.0
    - gnomon_package_imageenhancement=0.5.0
    - gnomon_package_tissuemesh=0.3.0
    - gnomon_package_tissueimagemesh=0.3.0
    - gnomon_package_treelsystem=0.5.0
    - pyside6
    - qtpy=2.0
    - qtconsole-base=5.2
    - jedi=0.18.2
    - python-lsp-server=1.7.1
    - pip

app:
  entry: gnomon # [linux]
  entry: gnomon # [osx]
  summary: Gnomon is a computational platform to analyse and simulate the development of life forms in 3D
#  icon: ../../assets/gnomon_logo.png
  type: desk


about:
  home: https://gnomon.gitlabpages.inria.fr/gnomon
  license: CECILL-C
  summary:  Gnomon is a computational platform to analyse and simulate the development of life forms in 3D
